# common config
save_path: "../../experiments/REO-nusOpenOcc/"
seed: 42
gpu: "0,1,2,3" 
print_frequency: 2
n_threads: 8
experiment_id: "exp_timestamp"

# data conifg
val_only: false
is_debug: false
n_epochs: 25
batch_size: [4, 8]
lr: 0.0004
warmup_epochs: 1
momentum: 0.9
weight_decay: 0.01 #
val_frequency: 1

dataset: "nuScenesOpenOcc" # 
data_root: "/path/to/dataset/OpenOcc_nuScenes/"
source_data_root: "/path/to/dataset/nuscenes"

grid_size: 0.2
img_size: [448, 800]
crop_img_size: [448, 800]
voxel_range: [-51.2, 51.2, -51.2, 51.2, -5, 3]
num_pc_voxels: 10240
num_images: 6
use_multi_sweeps: false
voxel_downscales: 8
use_pcd: true
use_img: true
use_radar: false

use_proj_loss: true
w_focal: 1.0
w_dice: 1.0
w_rgb: 1.0
w_depth: 2.0

net_type: "REONet" #
backbone: "resnet50" # "resnet50" | "resnet50_wide"| "resnet101" | "efficientnet_b7" | "swin_t"
imgnet_pretrained: true
pretrained_model_root: "/path/to/imgnet_pretrained_model"
num_classes: 17 # 1 free + 16cls
num_sem_classes: 17 # 1 unknown + 16cls
empty_idx: 0 # zero is empty

cls_freq: [
  1.02258412e+07, 3.29442410e+02, 2.48890864e+01, 7.58506932e+02,
  4.46649481e+03, 3.67149556e+02, 4.11173836e+01, 3.47466690e+02,
  1.42391930e+02, 9.17757981e+02, 1.95958578e+03, 8.01534274e+04,
  1.81147512e+03, 2.29635516e+04, 3.08883741e+04, 5.14078735e+04,
  6.13009194e+04]

# cehckpoint model
checkpoint: null
pretrained_model: null 
img_pretrained_model: null

# options for inference, used in infer_xxx.py
save_infer_result: false
infer_path: "/path/to/exp/folder"
infer_model: "best_SSCMeanIoU_model.pth"