# common config
save_path: "../../experiments/QueryOcc-SemanticKITTI/"
seed: 42
gpu: "0,1,2,3"
print_frequency: 2
n_threads: 8
experiment_id: "exp_timestamp"

# data conifg
val_only: false
is_debug: false
n_epochs: 25
batch_size: [2, 4]
lr: 0.0004
warmup_epochs: 1

momentum: 0.9
weight_decay: 0.01
val_frequency: 1

dataset: "SemanticKITTI"
data_root: "/path/to/dataset/semantickitti"
source_data_root: null

grid_size: 0.2
img_size: [352, 1184]
crop_img_size: [352, 1184]
voxel_range: [0, 51.2, -25.6, 25.6, -2, 4.4]
num_pc_voxels: 20480
num_images: 1
voxel_downscales: 4
use_multi_sweeps: false
use_pcd: true
use_img: true
use_radar: false

use_proj_loss: true
w_focal: 1.0
w_dice: 1.0
w_rgb: 1.0
w_depth: 2.0

net_type: "REONet" #
backbone: "resnet50" # "resnet50" | "resnet50_wide"| "resnet101" | "efficientnet_b7"
imgnet_pretrained: true
pretrained_model_root: "/path/to/imgnet_pretrained_model"
num_classes: 20 # 19 cls + 1 empty
num_sem_classes: 20 # 19 cls + 1 empty
empty_idx: 0 # zero is empty

cls_freq: [
  1.41308747e+06, 4.12174098e+03, 3.28858338e+01, 3.10680084e+01,
  1.69179665e+02, 2.14081861e+02, 6.83840565e+01, 7.43024046e+01,
  5.34041296e+01, 1.60949622e+04, 1.17294480e+03, 1.17151814e+04,
  5.92120178e+02, 1.48375842e+04, 4.10573340e+03, 4.13596197e+04,
  5.38185991e+02, 9.63746367e+03, 3.00811239e+02, 8.75878202e+01
]

# cehckpoint model
checkpoint: null
pretrained_model: null
img_pretrained_model: null 

# options for inference, used in infer_xxx.py
save_infer_result: false
infer_path: "/path/to/exp/folder"
infer_model: "best_SSCMeanIoU_model.pth"